# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /book-management

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN yarn

# Copy all source code to the working directory
COPY . .

# Expose the port that the app will run on
EXPOSE 5001

# Command to start the app
CMD [ "yarn", "start" ]
